### ISSUE TITLE
Further improvements

### ISSUE THREAD

**Issue by rhaschke** [ubi-agni/ros-builder-action#3]
### Speed
- [ ] Use [eatmydata](https://packages.debian.org/de/sid/eatmydata)?
- [ ] Use layered chroot: base (ro) - populated (rw) - sbuild (volatile)
  This will allow to enable `populated` as default and fallback to base on failure automatically.  
  For example, gazebo requiring ogre 9.0 conflicts with rviz using ogre 12.x  
- [ ] Skip a package if its dependencies are not available

### TODO
- [x] Check and fix security using `eval`: Only expand vars, but don't allow subshell execution?
  https://www.baeldung.com/linux/bash-safe-use-eval
- [ ] Fix `ici_filter` usage
  - [ ] Output of `ici_apt_install` is not filtered?!
  - [ ] Use `ici_quiet` for `bloom-generate` and `sbuild`? Optionally, create full output again.
- [ ] Replace deprecated `apt-key`.
  https://askubuntu.com/questions/1286545/what-commands-exactly-should-replace-the-deprecated-apt-key
  https://wiki.debian.org/SecureApt#How_to_find_and_add_a_key

### Features
- [ ] Implement `CONTENT_MODE=newer`: only keep newest package files
- [ ] Maintain the _database_ of actually build sources (with commit sha) in a `sources.repos` file on the deploy repository.
  - [ ] Optionally? use that version when rebuilding downstream packages in the repo
  - python helper to add, query, etc that database.
- [ ] Merge `remote.yaml` and `local.yaml` into `ros-$ROS_DISTRO.yaml`?
- [ ] Create docker image for use in CI builds (e.g. MoveIt, MTC)
- [ ] Deploy to [reprepro](https://wiki.ubuntuusers.de/reprepro)
  - [ ] Setup a TF-hosted webserver for `reprepro`
    - [ ] Generate keys for https and to sign `.debs`: https://letsencrypt.org/de/getting-started
- [ ] Support `rosdistro` package index for `ROS_SOURCES`
  This should allow building existing ROS distros on custom debian distros
